config/routes.rb
Rails.application.routes.draw do
  resources :votescomments
  resources :replies
  
  resources :comments do 
    put 'vote', on: :member
    put 'unvote', on: :member
  end
  resources :contributions do
    put 'vote', on: :member
    put 'unvote', on: :member
  end
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'contributions#index'
 # post '/comments', as: :create_comment
 
  get "/logout", to: "sessions#destroy"
  get '/auth/:provider/callback', to: 'sessions#omniauth'
 
  get '/newest', to: 'contributions#newest', as: :newest
  get '/asks', to: 'contributions#ask', as: :asks
  get "/notlog", to: "contributions#showNotLogMessage"
  get '/contributions/:id', to: 'contributions#show', as: :show_contributions
  get '/contributionsUser/:idUser', to: 'contributions#contributionsUser', as: :show_submissionsUser
  get '/upvotedsubmissions', to: 'contributions#upvotedContributions', as: :show_upvotedContributions
  
  get '/comments/:id', to: 'comments#show', as: :show_comments
  get '/commentsUser/:idUser', to: 'comments#commentsUser', as: :show_commentsUser
  get '/upvotedComments', to: 'comments#upvotedComments', as: :show_upvotedComments
  
  get '/users/:id', to: 'users#show', as: :show_users
  get '/users/:id/edit', to: 'users#edit', as: :edit_users
    
end

app/models/reply.rb
class Reply < ApplicationRecord
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :set_reply, only: [:show, :edit, :update, :destroy]

  # GET /replies
  # GET /replies.json
  def index
    @replies = Reply.all
  end

  # GET /replies/1
  # GET /replies/1.json
  def show
  end

  # GET /replies/new
  def new
    @reply = Reply.new
  end

  # GET /replies/1/edit
  def edit
  end

  # POST /replies
  # POST /replies.json
  def create
    @reply = Reply.new(reply_params)
    
    respond_to do |format|
      if (request.headers["X-API-KEY"].nil?)
        format.json { render json: {status: 401, error: "Unauthorized", message: "You provided no api key (X-API-KEY Header)"}, status: 401 }
      elsif (User.all.find_by(token: request.headers["X-API-KEY"]).nil?)
        format.json { render json: {status: 403, error: "Forbidden", message: "Your api key (X-API-KEY Header) is not valid"}, status: 403 }
      else
        session[:user] = User.all.find_by(token: request.headers["X-API-KEY"])
        
        if (@reply.text.empty?)
          format.json { render json: {status: 400, error: "Bad Request", message: "FIELDS MUST BE FILLED: title, url or text"}, status: 400 }
        else
          if @reply.save
            @comment = Comment.new(text: @reply.text, author_id: session[:user]["id"], author: session[:user]["name"], comments_id: @reply.comm_id, contributions_id: Comment.all.find_by(id: @reply.comm_id).contributions_id)
            @comment.save
            @reply.update(repl_id: @comment.id)
            
            format.html { redirect_to show_contributions_path(@comment.contributions_id)}
            format.json { render json: {new_reply: @reply, api_key: request.headers["X-API-KEY"]}, status: 201}
              
          else
            format.html { render :new }
            format.json { render json: @reply.errors, status: :unprocessable_entity }
          end
        end
      end
    end
  end

  # PATCH/PUT /replies/1
  # PATCH/PUT /replies/1.json
  def update
    respond_to do |format|
      if @reply.update(reply_params)
        format.html { redirect_to @reply, notice: 'Reply was successfully updated.' }
        format.json { render :show, status: :ok, location: @reply }
      else
        format.html { render :edit }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1
  # DELETE /replies/1.json
  def destroy
    @reply.destroy
    respond_to do |format|
      format.html { redirect_to replies_url, notice: 'Reply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reply
      @reply = Reply.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reply_params
      params.require(:reply).permit(:comm_id, :repl_id, :text, :root_id)
    end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.erb
<%= form_with(model: reply) do |form| %>
  <% if reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
        <% reply.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :comm_id, value: @comment.id %>
  <%= form.hidden_field :root_id, value: @comment.contributions_id %>
  <%= form.text_area :text, size: "60x6"%>
  <br><br>
  <%= form.submit "reply"%>
  
<% end %>

app/views/replies/edit.html.erb
<h1>Editing Reply</h1>

<%= render 'form', reply: @reply %>

<%= link_to 'Show', @reply %> |
<%= link_to 'Back', replies_path %>

app/views/replies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Replies</h1>

<table>
  <thead>
    <tr>
      <th>Comm</th>
      <th>Repl</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @replies.each do |reply| %>
      <tr>
        <td><%= reply.comm_id %></td>
        <td><%= reply.repl_id %></td>
        <td><%= link_to 'Show', reply %></td>
        <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
        <td><%= link_to 'Destroy', reply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reply', new_reply_path %>

app/views/replies/new.html.erb
<h1>New Reply</h1>

<%= render 'form', reply: @reply %>

<%= link_to 'Back', replies_path %>