config/routes.rb
Rails.application.routes.draw do
  resources :votescomments
  resources :replies
  
  resources :comments do 
    put 'vote', on: :member
    put 'unvote', on: :member
  end
  resources :contributions do
    put 'vote', on: :member
    put 'unvote', on: :member
  end
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'contributions#index'
 # post '/comments', as: :create_comment
 
  get "/logout", to: "sessions#destroy"
  get '/auth/:provider/callback', to: 'sessions#omniauth'
 
  get '/newest', to: 'contributions#newest', as: :newest
  get '/asks', to: 'contributions#ask', as: :asks
  get "/notlog", to: "contributions#showNotLogMessage"
  get '/contributions/:id', to: 'contributions#show', as: :show_contributions
  get '/contributionsUser/:idUser', to: 'contributions#contributionsUser', as: :show_submissionsUser
  get '/upvotedsubmissions', to: 'contributions#upvotedContributions', as: :show_upvotedContributions
  
  get '/comments/:id', to: 'comments#show', as: :show_comments
  get '/commentsUser/:idUser', to: 'comments#commentsUser', as: :show_commentsUser
  get '/upvotedComments', to: 'comments#upvotedComments', as: :show_upvotedComments
  
  get '/users/:id', to: 'users#show', as: :show_users
  get '/users/:id/edit', to: 'users#edit', as: :edit_users
    
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy, :vote, :unvote]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
    respond_to do |format|
      format.json { render json: @comments, status: :ok }
    end
  end
  
  def commentsUser
    @comments = Comment.all.where(author_id: params[:idUser])
    respond_to do |format|
      format.json { render json: @comments, status: :ok }
    end
  end
  
  def upvotedComments
    
    respond_to do |format|
      
      if (request.headers["X-API-KEY"].nil?)
        format.json { render json: {status: 401, error: "Unauthorized", message: "You provided no api key (X-API-KEY Header)"}, status: 401 }
      elsif (User.all.find_by(token: request.headers["X-API-KEY"]).nil?)
        format.json { render json: {status: 403, error: "Forbidden", message: "Your api key (X-API-KEY Header) is not valid"}, status: 403 }
      else
        session[:user] = User.all.find_by(token: request.headers["X-API-KEY"])
        @votescomments = Votescomment.all.where(user_id: session[:user]["id"])
        
        @comments = []
        @votescomments.each do |votescomment|
            @comments << Comment.all.find_by(id: votescomment.comment_id)
        end
        format.json { render json: @comments, status: :ok}
      end
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    respond_to do |format|
      format.json { render json: @comment, status: :ok }
    end
  end
  
  def vote
    respond_to do |format|
      
      session[:user] = User.all.find_by(token: request.headers["X-API-KEY"])
      
      if (request.headers["X-API-KEY"].nil?)
        format.json { render json: {status: 401, error: "Unauthorized", message: "You provided no api key (X-API-KEY Header)"}, status: 401 }
      elsif (User.all.find_by(token: request.headers["X-API-KEY"]).nil?)
        format.json { render json: {status: 403, error: "Forbidden", message: "Your api key (X-API-KEY Header) is not valid"}, status: 403 }
      elsif !Votescomment.all.find_by(comment_id: @comment.id, user_id: session[:user]["id"]).nil?
        format.json { render json: {status: 400, error: "Bad Request", message: "You have already voted it"}, status: 400 }
      else
        @votescomment = Votescomment.new(comment_id: @comment.id, user_id: session[:user]["id"])
        @votescomment.save
        format.html { redirect_to request.referrer}
        format.json { render json: {message: "Voted successfully"}, status: :ok}
      end
    end
  end
  
  def unvote
    respond_to do |format|
      
      session[:user] = User.all.find_by(token: request.headers["X-API-KEY"])
      
      if (request.headers["X-API-KEY"].nil?)
        format.json { render json: {status: 401, error: "Unauthorized", message: "You provided no api key (X-API-KEY Header)"}, status: 401 }
      elsif (User.all.find_by(token: request.headers["X-API-KEY"]).nil?)
        format.json { render json: {status: 403, error: "Forbidden", message: "Your api key (X-API-KEY Header) is not valid"}, status: 403 }
      elsif Votescomment.all.find_by(comment_id: @comment.id, user_id: session[:user]["id"]).nil?
        format.json { render json: {status: 400, error: "Bad Request", message: "You must vote it before"}, status: 400 }
      else
        @votescomment = Votescomment.all.find_by(comment_id: @comment.id, user_id: session[:user]["id"])
        @votescomment.destroy
        format.html { redirect_to request.referrer}
        format.json { render json: {message: "Unvoted successfully"}, status: :ok}
      end
    end
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    
    respond_to do |format|
      if (request.headers["X-API-KEY"].nil?)
        format.json { render json: {status: 401, error: "Unauthorized", message: "You provided no api key (X-API-KEY Header)"}, status: 401 }
      elsif (User.all.find_by(token: request.headers["X-API-KEY"]).nil?)
        format.json { render json: {status: 403, error: "Forbidden", message: "Your api key (X-API-KEY Header) is not valid"}, status: 403 }
      else
        session[:user] = User.all.find_by(token: request.headers["X-API-KEY"])
        
        if (@comment.text.empty?)
          format.json { render json: {status: 400, error: "Bad Request", message: "FIELDS MUST BE FILLED: title, url or text"}, status: 400 }
        else
          @comment.author_id = session[:user]["id"]
          @comment.author = session[:user]["name"]
          if @comment.save
            format.html { redirect_to show_contributions_path(@comment.contributions_id) }
            format.json { render json: {new_comment: @comment, api_key: request.headers["X-API-KEY"]}, status: 201 }
          else
            format.html { render :new }
            format.json { render json: @comment.errors, status: :unprocessable_entity }
          end
        end
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:text, :contributions_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, method:"post") do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form.hidden_field :contributions_id, value: @contribution.id %>
  <%= form.text_area :text, size: "60x6"%>
  <br><br>
  <%= form.submit "add comment"%>
  
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<html lang="en" op="news"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="shortcut icon" href="favicon.ico">
      <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
      <title>Hacker News</title></head><body><center><table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
      <tr>
        <td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px">
        <tr><td style="width:18px;padding-right:4px"><%= link_to image_tag('hacker-news.png'), contributions_path %></td>
        <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a><%= link_to 'Hacker News', contributions_path %></a></b>

        <a><%= link_to 'new', newest_path %></a> | 
        <% if !session[:user].nil? %>
          <a><%= link_to 'threads', show_commentsUser_path(session[:user]["id"]) %></a> | 
        <% end %>
        <a href="front">past</a> | <a href="newcomments">comments</a> | <a><%= link_to 'ask', asks_path %></a> | <a href="show">show</a> | <a href="jobs">jobs</a> | 
        <a><%= link_to 'submit', new_contribution_path %></a>
        
        </span></td><td style="text-align:right;padding-right:4px;"><span class="pagetop"><%= link_to session[:user]["name"], edit_users_path(session[:user]["id"]) %> | <%= link_to "logout", logout_path%></span></td></tr></table></td>
      </tr> 
      
      <tr id="pagespace" title="" style="height:10px"></tr>
      <tr><td><table border="0" cellpadding="0" cellspacing="0" class="itemlist">
        
      <% @comments.each do |comment| %>
        <% @contribution = Contribution.all.find_by(id: comment.contributions_id) %>
        <tr class='athing comtr' id='26841716'><td><table border='0'>
        <tr>
        <td class="ind"><img src="" height="1" width="20"></td>
        <td class="default">
        <div style="margin-top:2px; margin-bottom:-5px;">
        <span class="comhead">
        <a>
          <% if Votescomment.all.find_by(comment_id: comment.id, user_id: session[:user]["id"]).nil? %>
            <%= link_to '⇧', vote_comment_path(comment), method: :put %>
          <% else %>
            <%= link_to '⇩', unvote_comment_path(comment), method: :put %>
          <% end %>
        </a> | 
        <a><%= link_to comment.author, show_users_path(User.all.find_by(id: comment.author_id)) %></a> <span class="age"><a><%= comment.created_at %></a></span> | 
        <% if !comment.comments_id.nil? %>
          <%= link_to 'parent', show_comments_path(Comment.all.find_by(id: comment.comments_id)) %>
        <% end %>
        <span class='storyon'> | on: <%= link_to @contribution.title, show_contributions_path(@contribution) %></span>
        </span></div><br>
        <div class="comment"><span class="commtext c00"><%= comment.text %></span>
        <div class='reply'><p><font size="1"><u><%= link_to 'reply', show_comments_path(comment) %></u></font>
        </div></div></td>
        <br></tr>
        
        </table></td></tr>
      <% end %>
      
</table>
</td></tr>
<tr><td><img src="s.gif" height="10" width="0"><table width="100%" cellspacing="0" cellpadding="1"><tr><td bgcolor="#ff6600"></td></tr></table><br><center><a href="https://www.ycombinator.com/apply/">
        Applications are open for YC Summer 2021
      </a></center><br><center><span class="yclinks"><a href="newsguidelines.html">Guidelines</a>
        | <a href="newsfaq.html">FAQ</a>
        | <a href="lists">Lists</a>
        | <a href="https://github.com/HackerNews/API">API</a>
        | <a href="security.html">Security</a>
        | <a href="http://www.ycombinator.com/legal/">Legal</a>
        | <a href="http://www.ycombinator.com/apply/">Apply to YC</a>
        | <a href="mailto:hn@ycombinator.com">Contact</a></span><br><br><form method="get" action="//hn.algolia.com/">Search:
          <input type="text" name="q" value="" size="17" autocorrect="off" spellcheck="false" autocapitalize="off" autocomplete="false"></form>
            </center></td></tr>
      </table></center></body><script type='text/javascript' ></script></html>

app/views/comments/new.html.erb
<%= render 'form', comment: @comment %>

app/views/comments/show.html.erb
<% @contribution = Contribution.all.find_by(id: @comment.contributions_id) %>

<html lang="en" op="reply"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="favicon.ico">
        <title>Add Comment | Hacker News</title></head><body><center><table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
        <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><%= link_to image_tag('hacker-news.png'), contributions_path %></td>
        <td style="line-height:12pt; height:10px;"><span class="pagetop"><b>Add Comment</b></span></td></tr></table></td></tr>
        
<tr id="pagespace" title="Add Comment" style="height:10px"></tr><tr><td><table class="fatitem" border="0">
    <tr class='athing' id='26863933'><td class='ind'></td>
      <td valign="top" class="votelinks"><center><a>
        <% if Votescomment.all.find_by(comment_id: @comment.id, user_id: session[:user]["id"]).nil? %>
          <%= link_to '⇧', vote_comment_path(@comment), method: :put %>
        <% else %>
          <%= link_to '⇩', unvote_comment_path(@comment), method: :put %>
        <% end %>
      </a></center></td>
      <td class="default"><div style="margin-top:2px; margin-bottom:-10px;">
        <span class="comhead"><a><%= @comment.author %></a> 
        <span class="age"><a href="item?id=26863933"><%= @comment.created_at %></a></span> 
        <span id="unv_26863933"></span><span class="par"> | 
        <% if !@comment.comments_id.nil? %>
          <%= link_to 'parent', show_comments_path(Comment.all.find_by(id: @comment.comments_id)) %>
        <% end %>
        <span class='storyon'> | on: <%= link_to @contribution.title, show_contributions_path(@contribution) %> </span>
        </span></div>
        <br>
        <div class="comment"><span class="commtext c00"> <a><%= @comment.text %></a></span>
              
        <%= render '/replies/form', reply: Reply.new %>
      </td>
    </tr>
    
</table></td></tr></table></center></body><script type='text/javascript'></script></html>