config/routes.rb
Rails.application.routes.draw do
  resources :votescomments
  resources :replies
  
  resources :comments do 
    put 'vote', on: :member
    put 'unvote', on: :member
  end
  resources :contributions do
    put 'vote', on: :member
    put 'unvote', on: :member
  end
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'contributions#index'
 # post '/comments', as: :create_comment
 
  get "/logout", to: "sessions#destroy"
  get '/auth/:provider/callback', to: 'sessions#omniauth'
 
  get '/newest', to: 'contributions#newest', as: :newest
  get '/asks', to: 'contributions#ask', as: :asks
  get "/notlog", to: "contributions#showNotLogMessage"
  get '/contributions/:id', to: 'contributions#show', as: :show_contributions
  get '/contributionsUser/:idUser', to: 'contributions#contributionsUser', as: :show_submissionsUser
  get '/upvotedsubmissions', to: 'contributions#upvotedContributions', as: :show_upvotedContributions
  
  get '/comments/:id', to: 'comments#show', as: :show_comments
  get '/commentsUser/:idUser', to: 'comments#commentsUser', as: :show_commentsUser
  get '/upvotedComments', to: 'comments#upvotedComments', as: :show_upvotedComments
  
  get '/users/:id', to: 'users#show', as: :show_users
  get '/users/:id/edit', to: 'users#edit', as: :edit_users
    
end

app/models/user.rb
class User < ApplicationRecord
  
  def self.from_omniauth(response)
    User.find_or_create_by(uid: response[:uid], provider: response[:provider]) do |u| 
        u.name=response[:info][:name]
        u.email=response[:info][:email]
        u.password=response[:info][:password]
        u.token=response.credentials.token
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    respond_to do |format|
      format.json{ render json: {id: @user.id, name: @user.name, created_at: @user.created_at, about: @user.about}, status: :ok }
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    
    respond_to do |format|
      if (request.headers["X-API-KEY"].nil?)
        format.json { render json: {:status => 401, :error => "Unauthorized", :message => "You provided no api key (X-API-KEY Header)"}, status: 401 }
      elsif (@user.token != request.headers["X-API-KEY"])
        format.json { render json: {:status => 403, :error => "Forbidden", :message => "Your api key (X-API-KEY Header) is not valid"}, status: 403 }
      else    
        if @user.update(user_params)
          format.html { redirect_to :root }
          format.json { render json: {id: @user.id, name: @user.name, email: @user.email, created_at: @user.created_at, token: @user.token, about: @user.about, maxvisit: @user.maxvisit, minaway: @user.minaway, delay: @user.delay}, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :about, :maxvisit, :minaway, :delay)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<html lang="en" op="news"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="shortcut icon" href="favicon.ico">
      <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
      <title>Profile: <%= session[:user]["name"] %> | Hacker News</title></head><body><center><table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
      <tr>
        <td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px">
        <tr><td style="width:18px;padding-right:4px"><%= link_to image_tag('hacker-news.png'), contributions_path %></td>
        <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a><%= link_to 'Hacker News', contributions_path %></a></b>
        
        <a><%= link_to 'new', newest_path %></a> | <a href="threads?id=longchen">threads</a> | <a href="front">past</a> | <a href="newcomments">comments</a> | <a><%= link_to 'ask', asks_path %></a> | <a href="show">show</a> | <a href="jobs">jobs</a> | 
        
        <a><%= link_to 'submit', new_contribution_path %></a>
        </span></td><td style="text-align:right;padding-right:4px;"><span class="pagetop"><%= session[:user]["name"] %> (0) | <%= link_to "logout", logout_path%></span></td></tr></table></td>
      </tr>  
              
              
<tr id="pagespace" title="Profile: "<%= session[:user]["name"] %> style="height:10px"></tr><tr><td>
  <table border="0" cellpadding="0" cellspacing="0"><tr><td bgcolor="#ffffaa"><table cellpadding="5" width="100%"><tr><td>Please put a valid address in the email field, or we won't be able to
    send you a new password if you forget yours.  Your address is only
    visible to you and us.  Crawlers and other users can't see it.
  </td></tr></table></td></tr></table>

  <form class="profileform" method="put" action="/xuser"><input type="hidden" name="id" value="longchen"><input type="hidden" name="hmac" value="44cf94f8f211251ce1a96cbf310e9b3a7b77b2c5">
<table border="0">
  <tr class='athing'><td valign="top">user:</td><td><a><%= user.name %></a></td></tr>
  <tr><td valign="top">created:</td><td><a><%= user.created_at %></a></td></tr>
  <tr><td valign="top">karma:</td><td><a><%= user.karma %></a></td></tr>
  <tr><td valign="top">about:</td><td style="overflow:hidden;">
    <textarea cols="60" rows="5" wrap="virtual" name="user[about]"><%= user.about %></textarea>
    <font size="-2"><a href="formatdoc" tabindex="-1"><font color="#afafaf">help</font></a></font>
  </td></tr>
  <tr><td valign="top">email:</td><td><a><%= user.email %></a></td></tr>
  <tr><td valign="top">token:</td><td><a><%= user.token %></a></td></tr>
  <tr><td valign="top">showdead:</td><td><select name="user[showdead]"><option>yes</option><option selected> 
    <% if user.showdead == 'no' %> no
    <% else %> yes
    <% end %>
  </option></select></td></tr>
  <tr><td valign="top">noprocrast:</td><td><select name="user[noprocrast]"><option>yes</option><option selected>
    <% if user.noprocrast == 'no' %> no
    <% else %> yes
    <% end %>
  </option></select></td></tr>
  <tr><td valign="top">maxvisit:</td><td><input type="text" name="user[maxvisit]" value=<%= user.maxvisit %> size="16"></td></tr>
  <tr><td valign="top">minaway:</td><td><input type="text" name="user[minaway]" value=<%= user.minaway %> size="16"></td></tr>
  <tr><td valign="top">delay:</td><td><input type="text" name="user[delay]" value=<%= user.delay %> size="16"></td></tr>
  <tr><td></td><td><a href="changepw"><u>change password</u></a></td></tr>
  <tr><td></td><td><a><u><%= link_to 'submissions', show_submissionsUser_path(session[:user]["id"]) %></u></a></td></tr>
  <tr><td></td><td><a><u><%= link_to 'comments', show_commentsUser_path(session[:user]["id"]) %></u></a></td></tr>
  <tr><td></td><td><a href="hidden"><u>hidden</u></a></td></tr>
  <tr><td></td><td><a><u><%= link_to 'upvoted submissions', show_upvotedContributions_path %></u></a> / <a><u><%= link_to 'comments', show_upvotedComments_path %></u></a><span style='font-style:italic'>(private)</span></td></tr>
  <tr><td></td><td><a href="favorites?id=longchen"><u>favorite submissions</u></a> / <a href="favorites?id=longchen&amp;comments=t"><u>comments</u></a>&nbsp;<span style='font-style:italic'>(shared)</span></td></tr>
</table>
  <br><input type="submit" value="update" method="put"></form><br><br>
  
</td></tr></table></center></body><script type='text/javascript'></script></html>

<% end %>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<html lang="en" op="news"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="shortcut icon" href="favicon.ico">
      <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
      <title>Profile: <%= @user.name %> | Hacker News</title></head><body><center><table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
      <tr>
        <td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px">
        <tr><td style="width:18px;padding-right:4px"><%= link_to image_tag('hacker-news.png'), contributions_path %></td>
        <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a><%= link_to 'Hacker News', contributions_path %></a></b>
        
        <a><%= link_to 'new', newest_path %></a> | <a href="threads?id=longchen">threads</a> | <a href="front">past</a> | <a href="newcomments">comments</a> | <a><%= link_to 'ask', asks_path %></a> | <a href="show">show</a> | <a href="jobs">jobs</a> | 
        
        <a><%= link_to 'submit', new_contribution_path %></a>
        </span></td><td style="text-align:right;padding-right:4px;"><span class="pagetop"><%= session[:user]["name"] %> (0) | <%= link_to "logout", logout_path%></span></td></tr></table></td>
      </tr> 
      
      <tr id="pagespace" title="Profile: "+ <%= @user.name %> style="height:10px"></tr>
      
      <tr><td><table border="0">
        <tr class='athing'><td valign="top">user:</td><td timestamp="1371452252"><a><%= @user.name %></a></td></tr>
        <tr><td valign="top">created:</td><td><a><%= @user.created_at %></a></td></tr>
        <tr><td valign="top">karma:</td><td><a><%= @user.karma %></a></td></tr>
        <tr><td valign="top">about:</td><td style="overflow:hidden;"><a><%= @user.about %></a></td></tr>
        <tr><td></td><td><a><u><%= link_to 'submissions', show_submissionsUser_path(@user) %></u></a></td></tr>
        <tr><td></td><td><a><u><%= link_to 'comments', show_commentsUser_path(@user) %></u></a></td></tr>
        <tr><td></td><td><a href="favorites?id=sam_lowry_"><u>favorites</u></a></td></tr>
      </table><br><br></td></tr>
      
      </table></center></body><script type='text/javascript'></script></html>