config/routes.rb
Rails.application.routes.draw do
  resources :votescomments
  resources :replies
  
  resources :comments do 
    put 'vote', on: :member
    put 'unvote', on: :member
  end
  resources :contributions do
    put 'vote', on: :member
    put 'unvote', on: :member
  end
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'contributions#index'
 # post '/comments', as: :create_comment
 
  get "/logout", to: "sessions#destroy"
  get '/auth/:provider/callback', to: 'sessions#omniauth'
 
  get '/newest', to: 'contributions#newest', as: :newest
  get '/asks', to: 'contributions#ask', as: :asks
  get "/notlog", to: "contributions#showNotLogMessage"
  get '/contributions/:id', to: 'contributions#show', as: :show_contributions
  get '/contributionsUser/:idUser', to: 'contributions#contributionsUser', as: :show_submissionsUser
  get '/upvotedsubmissions', to: 'contributions#upvotedContributions', as: :show_upvotedContributions
  
  get '/comments/:id', to: 'comments#show', as: :show_comments
  get '/commentsUser/:idUser', to: 'comments#commentsUser', as: :show_commentsUser
  get '/upvotedComments', to: 'comments#upvotedComments', as: :show_upvotedComments
  
  get '/users/:id', to: 'users#show', as: :show_users
  get '/users/:id/edit', to: 'users#edit', as: :edit_users
    
end

app/models/contribution.rb
class Contribution < ApplicationRecord
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :set_contribution, only: [:show, :edit, :vote, :unvote, :update, :destroy]
  
  # GET /contributions
  # GET /contributions.json
  def index
    @contributions = Contribution.all.order(points: :desc)
    respond_to do |format|
      format.json { render json: @contributions, status: :ok }
    end
  end
  
  def newest
    @contributions = Contribution.all.order(created_at: :desc)
    respond_to do |format|
      format.json { render json: @contributions, status: :ok }
    end
  end
  
  def contributionsUser
    session[:user] = User.all.find_by(token: request.headers["X-API-KEY"])
    @contributions = Contribution.all.where(userID: params[:idUser])
    respond_to do |format|
      format.json { render json: @contributions, status: :ok }
    end
  end
  
  def upvotedContributions
    
    respond_to do |format|
      
      if (request.headers["X-API-KEY"].nil?)
        format.json { render json: {status: 401, error: "Unauthorized", message: "You provided no api key (X-API-KEY Header)"}, status: 401 }
      elsif (User.all.find_by(token: request.headers["X-API-KEY"]).nil?)
        format.json { render json: {status: 403, error: "Forbidden", message: "Your api key (X-API-KEY Header) is not valid"}, status: 403 }
      else
        session[:user] = User.all.find_by(token: request.headers["X-API-KEY"])
        @contributions_aux = Contribution.all
        @contributions = []
        
        @contributions_aux.each do |contribution|
          if (contribution.usersVoted.include?(','+ session[:user]["id"].to_s + ',') )
            @contributions << contribution
          end
        end
        format.json { render json: @contributions, status: :ok}
      end
    end
  end
  
  def ask
    @contributions = Contribution.where(url: "")
    respond_to do |format|
      format.json { render json: @contributions, status: :ok }
    end
  end
  
  def vote
    respond_to do |format|
      
      session[:user] = User.all.find_by(token: request.headers["X-API-KEY"])
      
      if (request.headers["X-API-KEY"].nil?)
        format.json { render json: {status: 401, error: "Unauthorized", message: "You provided no api key (X-API-KEY Header)"}, status: 401 }
      elsif (User.all.find_by(token: request.headers["X-API-KEY"]).nil?)
        format.json { render json: {status: 403, error: "Forbidden", message: "Your api key (X-API-KEY Header) is not valid"}, status: 403 }
      elsif (@contribution.usersVoted.include?(","+session[:user]["id"].to_s))
        format.json { render json: {status: 400, error: "Bad Request", message: "You have already voted it"}, status: 400 }
      else
        @contribution.usersVoted << session[:user]["id"].to_s+","
        @contribution.points = @contribution.points + 1
        @contribution.save
        format.html { redirect_to request.referrer }
        format.json { render json: {message: "Voted successfully"}, status: :ok}
      end
    end
  end
  
  def unvote
    respond_to do |format|
    
      session[:user] = User.all.find_by(token: request.headers["X-API-KEY"])
      
      if (request.headers["X-API-KEY"].nil?)
        format.json { render json: {status: 401, error: "Unauthorized", message: "You provided no api key (X-API-KEY Header)"}, status: 401 }
      elsif (User.all.find_by(token: request.headers["X-API-KEY"]).nil?)
        format.json { render json: {status: 403, error: "Forbidden", message: "Your api key (X-API-KEY Header) is not valid"}, status: 403 }
      elsif (@contribution.usersVoted.exclude?(","+session[:user]["id"].to_s))
        format.json { render json: {status: 400, error: "Bad Request", message: "You have already unvoted it"}, status: 400 }
      else
        @contribution.usersVoted.slice!(session[:user]["id"].to_s+",")
        @contribution.points = @contribution.points - 1
        @contribution.save
        format.html { redirect_to request.referrer }
        format.json { render json: {message: "Unvoted successfully"}, status: :ok}
      end
    end
  end
  
  # GET /contributions/1
  # GET /contributions/1.json
  def show
    @comments = Comment.all.where(contributions_id: params[:id])
    respond_to do |format|
      format.json { render json: @comments, status: :ok }
    end
  end

  # GET /contributions/new
  def new
    @contribution = Contribution.new
    
  end

  # GET /contributions/1/edit
  def edit
  end

  # POST /contributions
  # POST /contributions.json
  def create
    @contribution = Contribution.new(contribution_params)
    respond_to do |format|
      if (request.headers["X-API-KEY"].nil?)
        format.json { render json: {status: 401, error: "Unauthorized", message: "You provided no api key (X-API-KEY Header)"}, status: 401 }
      elsif (User.all.find_by(token: request.headers["X-API-KEY"]).nil?)
        format.json { render json: {status: 403, error: "Forbidden", message: "Your api key (X-API-KEY Header) is not valid"}, status: 403 }
      else
        session[:user] = User.all.find_by(token: request.headers["X-API-KEY"])
        @contribution.user = session[:user]["name"]
        @contribution.userID = session[:user]["id"]
        
        
            
        if @contribution.url.empty? || !Contribution.exists?(url: @contribution.url)
          
          if @contribution.title.empty? || (@contribution.url.empty? && @contribution.text.empty?)
            format.html { redirect_to new_contribution_path, alert: "FIELDS MUST BE FILLED: title, url or text" }
            format.json { render json: {status: 400, error: "Bad Request", message: "FIELDS MUST BE FILLED: title, url or text"}, status: 400 }
          elsif !@contribution.url.empty? && !@contribution.url.include?("https")
            format.html { redirect_to new_contribution_path, alert: "Wrong format of URL!" }
            format.json { render json: {status: 400, error: "Bad Request", message: "Wrong format of URL!"}, status: 400 }
          else 
            if @contribution.save
              
              if !@contribution.url.empty? && !@contribution.text.empty?
                 @comment = Comment.new(text: @contribution.text, author_id: @contribution.userID, author: @contribution.user, contributions_id: @contribution.id)
                 @comment.save
              end
              format.html { redirect_to newest_path}
              format.json { render json: {new_contribution: @contribution, api_key: request.headers["X-API-KEY"]}, status: 201}
                
            else
              format.html { render :new }
              format.json { render json: @contribution.errors, status: :unprocessable_entity }
            end
          end
        else
          format.html { redirect_to show_contributions_path(Contribution.all.find_by(url: @contribution.url)) }
          format.json { render json: {redirectedTo: Contribution.all.find_by(url: @contribution.url), message: "URL repeated"}, status: :ok}
        end
      end
    end
  end

  # PATCH/PUT /contributions/1
  # PATCH/PUT /contributions/1.json
  def update
    respond_to do |format|
      if @contribution.update(contribution_params)
        format.html { redirect_to @contribution, notice: 'Contribution was successfully updated.' }
        format.json { render :show, status: :ok, location: @contribution }
      else
        format.html { render :edit }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contributions/1
  # DELETE /contributions/1.json
  def destroy
    @contribution.destroy
    respond_to do |format|
      format.html { redirect_to contributions_url, notice: 'Contribution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def showNotLogMessage
    respond_to do |format|
      if (session[:user].nil?)
       format.html {redirect_to root_path, notice: "You have to be logged in to submit."}
      else 
       format.html {redirect_to root_path}
      end
    end
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contribution
      @contribution = Contribution.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contribution_params
      params.require(:contribution).permit(:title, :url, :points, :user, :text)
    end
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/views/contributions/_form.html.erb
<% if notice.nil? == false || alert.nil? == false %>
  <div class="warning">
    <p id="notice"><span style="color: green;"><%= notice %></span></p>
    <p id="alert"><span style="color: red;"><%= alert %></span></p>
  </div>
<% end %>

<%= form_with(model: contribution) do |form| %>
  <% if contribution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contribution.errors.count, "error") %> prohibited this contribution from being saved:</h2>

      <ul>
        <% contribution.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <html lang="en" op="submit"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="shortcut icon" href="favicon.ico"><title>Submit | Hacker News</title></head><body><center><table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef"><tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><%= link_to image_tag('hacker-news.png'), contributions_path %></td><td style="line-height:12pt; height:10px;"><span class="pagetop"><b>Submit</b></span></td></tr></table></td></tr><tr id="pagespace"Submit style="height:10px"></tr><tr><td><form method="post" action="/r"><input type="hidden" name="fnid" value="GAeIuxxvVBbxEgVCLzjf4z"><input type="hidden" name="fnop" value="submit-page"><script type="text/javascript">function tlen(el) { var n = el.value.length - 80; el.nextSibling.innerText = n > 0 ? n + ' too long' : ''; }</script><table border="0"><tr><td>title</td><td><input type="text" name="contribution[title]" size="50" oninput="tlen(this)" onfocus="tlen(this)"><span style="margin-left:10px"></span></td></tr><tr><td>url</td><td><input type="text" name="contribution[url]" size="50"></td></tr><tr><td></td><td><b>or</b></td></tr><tr><td>text</td><td><textarea name="contribution[text]" rows="4" cols="49"></textarea></td></tr><tr><td></td><td></td></tr>
  <div = class = "actions"><tr><td></td><td><input type="submit" value="submit" method="post" ></td></tr><tr style="height:20px"></tr></div>
  <tr><td></td><td>Leave url blank to submit a question for discussion. If there is no url, the text (if any) will appear at the top of the thread.<br><br>
  You can also submit via <a href="bookmarklet.html" rel="nofollow"><u>bookmarklet</u></a>.</td></tr></table></form></td></tr></table></center></body></html>

<% end %>

app/views/contributions/edit.html.erb
<h1>Editing Contribution</h1>

<%= render 'form', contribution: @contribution %>

<%= link_to 'Show', @contribution %> |
<%= link_to 'Back', contributions_path %>

app/views/contributions/index.html.erb
<% if notice.nil? == false || alert.nil? == false %>
  <div class="warning">
    <p id="notice"><span style="color: green;"><%= notice %></span></p>
    <p id="alert"><span style="color: red;"><%= alert %></span></p>
  </div>
<% end %>

<html lang="en" op="news"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="shortcut icon" href="favicon.ico">
      <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
      <title>Hacker News</title></head><body><center><table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
      <tr>
        <td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px">
        <tr><td style="width:18px;padding-right:4px"><%= link_to image_tag('hacker-news.png'), contributions_path %></td>
        <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a><%= link_to 'Hacker News', contributions_path %></a></b>

        <a><%= link_to 'new', newest_path %></a> | 
        <% if !session[:user].nil? %>
          <a><%= link_to 'threads', show_commentsUser_path(session[:user]["id"]) %></a> | 
        <% end %>
        <a href="front">past</a> | <a href="newcomments">comments</a> | <a><%= link_to 'ask', asks_path %></a> | <a href="show">show</a> | <a href="jobs">jobs</a> | 
        
        <% if session[:user].nil? %>
          <a><%= link_to 'submit', notlog_path %></a>
          </span></td><td style="text-align:right;padding-right:4px;"><span class="pagetop"><%= button_to "login", "/auth/google_oauth2"%></span></td></tr></table></td>
        <% else %>
          <a><%= link_to 'submit', new_contribution_path %></a>
          </span></td><td style="text-align:right;padding-right:4px;"><span class="pagetop"><%= link_to session[:user]["name"], edit_users_path(session[:user]["id"]) %> (0) | <%= link_to "logout", logout_path%></span></td></tr></table></td>
        <% end %>
      </tr>
        
  <tr id="pagespace" title="" style="height:10px"></tr>
  <tr><td><table border="0" cellpadding="0" cellspacing="0" class="itemlist">
    
    <% count = 1 %>
    <% @contributions.each do |contribution| %>
            <tr class='athing' id='26512720'>
            <td align="right" valign="top" class="title"><span class="rank"><%= count %>. |</span></td>
            <td><center>
              <% if session[:user].nil? %>
                <a style="color: orange;">*</a>
              <% elsif contribution.usersVoted.exclude?(","+session[:user]["id"].to_s+",") %>
                <%= link_to '⇧', vote_contribution_path(contribution), method: :put %>
              <% else %>
                <%= link_to '⇩', unvote_contribution_path(contribution), method: :put %>
              <% end %>
            </center></td>
            
            <td class="title">| 
            <% if contribution.url.empty? %>
              <a href= <%= show_contributions_path(contribution) %>> 
            <% else %>
              <a href= <%= contribution.url%>>
            <% end %>
            <span class="storylink"><%= contribution.title %></span></a><span class="sitebit comhead"> (<a><span class="sitestr"><%= contribution.url%></span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
            <span class="score" id="score_26512720"><%= contribution.points %> points</span> by <a><%= link_to contribution.user, show_users_path(User.all.find_by(id: contribution.userID)) %></a> <span class="age"><a><%= contribution.created_at %></a></span> <span id="unv_26512720"></span> | <a>hide</a> | <a><%= link_to 'comments', show_contributions_path(contribution) %></a></td></tr>
            <tr class="spacer" style="height:5px"></tr>
      <% count = count + 1 %>
    <% end %>
    
</table>
</td></tr>
<tr><td><img height="10" width="0"><table width="100%" cellspacing="0" cellpadding="1"><tr><td bgcolor="#ff6600"></td></tr></table><br><center><a href="https://www.ycombinator.com/apply/">
        Applications are open for YC Summer 2021
      </a></center><br><center><span class="yclinks"><a href="newsguidelines.html">Guidelines</a>
        | <a href="newsfaq.html">FAQ</a>
        | <a href="lists">Lists</a>
        | <a href="https://github.com/HackerNews/API">API</a>
        | <a href="security.html">Security</a>
        | <a href="http://www.ycombinator.com/legal/">Legal</a>
        | <a href="http://www.ycombinator.com/apply/">Apply to YC</a>
        | <a href="mailto:hn@ycombinator.com">Contact</a></span><br><br><form method="get" action="//hn.algolia.com/">Search:
          <input type="text" name="q" value="" size="17" autocorrect="off" spellcheck="false" autocapitalize="off" autocomplete="false"></form>
            </center></td></tr>
      </table></center></body><script type='text/javascript'></script></html>

app/views/contributions/new.html.erb
<%= render 'form', contribution: @contribution %>

app/views/contributions/show.html.erb
<% def draw_comment(comment, padding) %>
  <tr class='athing comtr' id='26841716'><td><table border='0'>
  <tr>
  <td class="ind"><img src="" height="1" width=<%= padding %>></td>
  <td class="default">
  <div style="margin-top:2px; margin-bottom:-10px;">
                  
  <a>
    <% if session[:user].nil? %>
      <a style="color: orange;">*</a>
    <% elsif Votescomment.all.find_by(comment_id: comment.id, user_id: session[:user]["id"]).nil? %>
      <%= link_to '⇧', vote_comment_path(comment), method: :put %>
    <% else %>
      <%= link_to '⇩', unvote_comment_path(comment), method: :put %>
    <% end %>
  </a>
  <span class="comhead">
  <a><%= link_to comment.author, show_users_path(User.all.find_by(id: comment.author_id)) %></a> <span class="age"><a><%= comment.created_at %></a></span> <span id="unv_26841716"></span><span class="par"></span><span class='storyon'></span>
  </span></div><br>
  <div class="comment"><span class="commtext c00"><%= comment.text %></span>
  <div class='reply'><p><font size="1"><u><%= link_to 'reply', show_comments_path(comment) %></u></font>
  </div></div></td>
  <br></tr>
  
  </table></td></tr>
<% end %>


<% def draw_fill_tree(comment, padding) %>
  <% Reply.all.where(comm_id: comment.id).each do |reply| %>
    
        <% @comment = Comment.all.find_by(id: reply.repl_id) %>

        <% draw_comment(@comment, padding) %>
        
        <% if !Reply.all.find_by(comm_id: @comment.id).nil? %>
          <% draw_fill_tree(@comment, padding + 40) %>
        <% end %>
  <% end %>
<% end %>


<html lang="en" op="news"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="shortcut icon" href="favicon.ico">
      <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
      <title>Hacker News</title></head><body><center><table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
      <tr>
        <td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px">
        <tr><td style="width:18px;padding-right:4px"><%= link_to image_tag('hacker-news.png'), contributions_path %></td>
        <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a><%= link_to 'Hacker News', contributions_path %></a></b>
        
        <a><%= link_to 'new', newest_path %></a> | <a href="threads?id=longchen">threads</a> | <a href="front">past</a> | <a href="newcomments">comments</a> | <a><%= link_to 'ask', asks_path %></a> | <a href="show">show</a> | <a href="jobs">jobs</a> | 
        
        <% if session[:user].nil? %>
          <a><%= link_to 'submit', notlog_path %></a>
          </span></td><td style="text-align:right;padding-right:4px;"><span class="pagetop"><%= button_to "login", "/auth/google_oauth2"%></span></td></tr></table></td>
        <% else %>
          <a><%= link_to 'submit', new_contribution_path %></a>
          </span></td><td style="text-align:right;padding-right:4px;"><span class="pagetop"><%= link_to session[:user]["name"], edit_users_path(session[:user]["id"]) %> (0) | <%= link_to "logout", logout_path%></span></td></tr></table></td>
        <% end %>
      </tr> 
              
      <tr id="pagespace" title=<%= @contribution.title %> style="height:10px"></tr><tr><td><table class="fatitem" border="0">
      <tr class='athing' id='26841385'><td align="right" valign="top" class="title"><span class="rank"></span></td>
      <td><center>
              <% if session[:user].nil? %>
                <a style="color: orange;">*</a>
              <% elsif @contribution.usersVoted.exclude?(","+session[:user]["id"].to_s+",") %>
                <%= link_to '⇧', vote_contribution_path(@contribution), method: :put %>
              <% else %>
                <%= link_to '⇩', unvote_contribution_path(@contribution), method: :put %>
              <% end %>
      </center></td>
      <td class="title"><a><%= @contribution.title %></a></td></tr><tr><td colspan="2"></td><td class="subtext">
      <span class="score" id="score_26841385"><%= @contribution.points %> points</span> by <a href="user?id=49yearsold" class="hnuser"><%= @contribution.user %></a> <span class="age"><a href="item?id=26841385"><%= @contribution.created_at %></a></span> <span id="unv_26841385"></span> | <a href="hide?id=26841385&amp;auth=6112994914be1bda129cba480607d04c58d01f62&amp;goto=item%3Fid%3D26841385">hide</a> | <a href="https://hn.algolia.com/?query=Ask%20HN%3A%20How%20to%20Get%20Sports%20Data%3F&type=story&dateRange=all&sort=byDate&storyText=false&prefix&page=0" class="hnpast">past</a> | <a href="fave?id=26841385&amp;auth=6112994914be1bda129cba480607d04c58d01f62">favorite</a> | <a href="item?id=26841385">1&nbsp;comment</a></td></tr>
      
      <% if @contribution.url.empty? %>
        <tr><td colspan="2"></td><td><%= @contribution.text %></td></tr>
      <% end %>
      
      <tr><td colspan="2"></td><td>
        <%= render '/comments/form', comment: Comment.new %>
      </td></tr>
      </table><br><br>
      
      
      <% padding = 0 %>
      <table border="0" class='comment-tree'>
        
          <% @comments.each do |comment| %>

              <% draw_comment(comment, 20) %>
              
              <% draw_fill_tree(comment, 60) %>

            <% end %>
          <% end %>
          
      </table>
      
      <br><br></td></tr>
      
<tr><td><img src="s.gif" height="10" width="0"><table width="100%" cellspacing="0" cellpadding="1"><tr><td bgcolor="#ff6600"></td></tr></table><br><center><span class="yclinks"><a href="newsguidelines.html">Guidelines</a>
        | <a href="newsfaq.html">FAQ</a>
        | <a href="lists">Lists</a>
        | <a href="https://github.com/HackerNews/API">API</a>
        | <a href="security.html">Security</a>
        | <a href="http://www.ycombinator.com/legal/">Legal</a>
        | <a href="http://www.ycombinator.com/apply/">Apply to YC</a>
        | <a href="mailto:hn@ycombinator.com">Contact</a></span><br><br><form method="get" action="//hn.algolia.com/">Search:
          <input type="text" name="q" value="" size="17" autocorrect="off" spellcheck="false" autocapitalize="off" autocomplete="false"></form>
            </center></td></tr>
      </table></center></body><script type='text/javascript'></script></html>